### ISSUE TITLE
Export functionality was removed?

### ISSUE THREAD

**Issue by allanonmage** [Universal-Debloater-Alliance/universal-android-debloater#130]
**Describe the bug**
There appears to be no way to export the list of selected options, like there is in v5 of the tool

**Expected behavior**
A button that makes a file called "uad_exported_selection.txt"

**You have a solution?**
Put the button back.

**UAD log**
n/a

**Comment by Frigyes06** [comment]
See:
https://github.com/0x192/universal-android-debloater/issues/192

Please open a feature request

**Comment by allanonmage** [comment]
The feature that was implemented in the linked post, in the previous version, no longer exists in the current version.  Since I was using the latest version of the other project, that means that this project has broken (possibly removed?) that functionality.  Since it was part of a button that no longer exists, idk which one it is.
