### ISSUE TITLE
UAD doesn't open

### ISSUE THREAD

**Issue by Dv5n** [Universal-Debloater-Alliance/universal-android-debloater#36]
**Describe the bug**
The UAD GUI doesn't open and I see in Task Manager the ADB.EXE at 0% CPU usage with the command line: "adb -L tcp:5037 fork-server server --reply-fd 504"

![is](https://github.com/Universal-Debloater-Alliance/universal-android-debloater/assets/118058649/1d16307f-d0f0-4bcd-8693-197ca208335b)

**Expected behavior**
UAD should open and display the GUI.

**You have a solution?**
No.

**UAD log**
"2023-11-06 14:51:36 WARN [C:\Users\runneradmin.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-hal-0.14.1\src\vulkan\adapter.rs:1069] Missing extensions: ["VK_KHR_maintenance2", "VK_KHR_storage_buffer_storage_class", "VK_EXT_sampler_filter_minmax", "VK_KHR_timeline_semaphore"]"

**More info**

It was working before but now it doesn't work (It was working some days before I opened this issue)

But then when it worked, UAD didn't recognize my device (Xiaomi Redmi Note 12 Pro 4G) i also have another device (Samsung Galaxy A20e) that also didn't recognize.

I have USB Debugging enabled on both.

![Screenshot_20231104-161205_Settings.jpg](https://github.com/Universal-Debloater-Alliance/universal-android-debloater/assets/118058649/b4221b45-52bc-4e17-9c5c-e31285725eb9)
Samsung Galaxy A20e

**Comment by Dv5n** [comment]
> Maybe try [uad_gui-windows-opengl.exe](https://github.com/Universal-Debloater-Alliance/universal-android-debloater/releases/download/0.6.0/uad_gui-windows-opengl.exe)?

I tried it.

**Comment by Frigyes06** [comment]
Any logs you could post?

**Comment by Dv5n** [comment]
> Any logs you could post?

How to see the log?

**Comment by ProtonOSS** [comment]
> > Any logs you could post?
> 
> How to see the log?

Log location: `%localappdata%\uad`
![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater/assets/131740614/c56063fe-e02c-428d-b415-2edbe183dd3f)

**Comment by Dv5n** [comment]
> > > Any logs you could post?
> > 
> > 
> > How to see the log?
> 
> Setting location `%appdata%\uad` Log location: `%localappdata%\uad` ![image](https://user-images.githubusercontent.com/131740614/280497163-c56063fe-e02c-428d-b415-2edbe183dd3f.png)

Thanks, here's the log

"2023-11-06 14:51:36 WARN  [C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-hal-0.14.1\src\vulkan\adapter.rs:1069] Missing extensions: ["VK_KHR_maintenance2", "VK_KHR_storage_buffer_storage_class", "VK_EXT_sampler_filter_minmax", "VK_KHR_timeline_semaphore"]"

**Comment by Dv5n** [comment]
> I'm not an expert but it looks like vulkan drivers are missing?
> By my understanding the `VK` stands for `Vulkan` so it's related, but not sure about the error or how to solve it.

I think it's because i have some problems with OpenGL/Vulkan.

I was having some problems in the past, SM64EX-Coop with OpenGL didn't open. But after an update to Windows, it fixed my problems.

But i think there's still a problem, Minecraft (after my pc gets a little bit hot) it glitches the graphics.

And when it happens it scares me.

**Comment by Dv5n** [comment]
But it's weird because i have set W: as the main windows directory.

But i still have the C: for extra compatibility.

**Comment by Dv5n** [comment]
Thanks, Now works perfectly.
I can finally destroy Netflix from my samsung galaxy A20e.
