### ISSUE TITLE
Backup / Restore UI Broken On Linux (OpenGL)

### ISSUE THREAD

**Issue by ShellCadium** [Universal-Debloater-Alliance/universal-android-debloater#45]
**Description:**

This bug occurs, while trying to access the backup / restore menu in settings. The UI elements appear broken, as visible in the attached screenshot. 

![broken](https://github.com/Universal-Debloater-Alliance/universal-android-debloater/assets/143310530/47840ec0-56a4-4844-bca5-cd0bd20eb544)

**Expected behavior**

The UI elements are rendered properly.

**You have a solution?**

The fix would be to align it correctly, as the functionality does actually work as intended, ie: generates a .json file with the selections.

**Comment by Frigyes06** [comment]
Wayland or Xorg?
Also, can you post logs?

**Comment by Frigyes06** [comment]
OH WOW
Yes, I can reproduce. If I decrease the vertical size of my screen. It doesn't switch to a scroll mode or something. Super weird.
![image](https://github.com/Universal-Debloater-Alliance/universal-android-debloater/assets/72750891/8094910c-17fc-4f2d-be15-963d910990a6)

This is definitely a bug

**Comment by Frigyes06** [comment]
Fixed by #117
