### ISSUE TITLE
The lists contains user apps

### ISSUE THREAD

**Issue by Skizzy24** [Universal-Debloater-Alliance/universal-android-debloater#50]
**Describe the bug**
I was uninstalling apps in the recommended list when it showed the Google Docs app, but its not a system app so i can uninstall it myself

**Expected behavior**
The program does show only system apps

**You have a solution?**
No

**Comment by Frigyes06** [comment]
This is not a bug, but a feature. The program is supposed to list user apps too. We could add a toggle to turn it on and off maybe?

**Comment by Frigyes06** [comment]
> I feel like it used to only show system apps? I'd also find that more logical... don't need a Bloatware remover to remove those anyway..

It did. Newest release (pending) reverts it to system apps only.

**Comment by AnonymousWP** [comment]
> > I feel like it used to only show system apps? I'd also find that more logical... don't need a Bloatware remover to remove those anyway..
> 
> It did. Newest release (pending) reverts it to system apps only.

Can you link your PR to this issue?
