### ISSUE TITLE
Cannot execute on Debian 11

### ISSUE THREAD

**Issue by geoderix** [Universal-Debloater-Alliance/universal-android-debloater#52]
When I try to run the program on Debian 11, I get the following messages:

`$ ./uad_gui-linux
./uad_gui-linux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./uad_gui-linux)
./uad_gui-linux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./uad_gui-linux)
./uad_gui-linux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./uad_gui-linux)
./uad_gui-linux: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./uad_gui-linux)`

or

$ ./uad_gui-linux
./uad_gui-linux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./uad_gui-linux)
./uad_gui-linux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./uad_gui-linux)
./uad_gui-linux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./uad_gui-linux)
./uad_gui-linux: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./uad_gui-linux)`

Debian 11 has glibc version 2.31.

Please fix it to run the program on Debian 11 (and other less recent distributions).

Thank you.

P.S. The old version of the program (from 0x192) runs normally on Debian 11.

**Comment by Frigyes06** [comment]
```sudo apt-get update && sudo apt get upgrade```

If that doesn't work, you'll have to build from source.

**Comment by geoderix** [comment]
Thank you, great advice!
In the releases of Debian, the version of system libraries are not updated.
Debian 11 is a very common distribution.
I will not build it myself, I don’t know how to do this and I do not want to do it. Especially not on rust.
Correct if possible. If it is not possible, I will use the original program.
Best wishes.

**Comment by Frigyes06** [comment]
The CI builder runs Ubuntu 22.04
The only fix is someone building the software with outdated glibc, which neither me or the CI pipeline has. Nor do I have interest in maintaining outdated software. Building from source is easy and fast, but it's your decision in the end.

**Comment by geoderix** [comment]
Thank you very much!
If it's so easy to build the program, why can't you build it easily?
Why should I care about your СI builder?
Debian 11 is not a outdated distribution. The transition to Debian 12 is just beginning.
It's your decision whether to rebuild for users or not. If not, then why put the program in a public repository without warning on which distributions it works and which it doesn’t work? Why don't you appreciate my time? Why do you need a buglist? To advise people to build themselves?
All the best in providing such advice and guidance.

**Comment by Frigyes06** [comment]
I can build it. But I have the newer glibc too. The CI pipeline is what produces the artifacts for the releases on GitHub, it's the process building the app into binaries. Debian 11 is indeed not eol yet, I have no clue why they don't update their libraries. It's a public repo so people can inspect the code, modify and build it to their liking. 

If you or anyone wants to take the time and make a CI script that builds for older glibc, I have no issue with that, but I personally will not create or maintain anything supporting the use of outdated software. It's not worth my time.
