### ISSUE TITLE
com.qualcomm.qcrilmsgtunnel

### ISSUE THREAD

**Issue by Obegg** [Universal-Debloater-Alliance/universal-android-debloater#55]
**Your phone model**:
OnePlus 7

**Describe the issue**
Uninstalling `com.qualcomm.qcrilmsgtunnel` (Which is on `recommended` list) and then reboot to my OnePlus 7 results in error when trying to call and message any number.

**You have a solution?**
Restore `com.qualcomm.qcrilmsgtunnel`

**Comment by Frigyes06** [comment]
It was probably the AnonymousWP mega merger, or blitz's fix. Thank you for pointing this out. We'll resolve it asap

**Comment by AnonymousWP** [comment]
Opened a PR and changed it to `Expert`. I also added a warning to the description.

**Comment by AnonymousWP** [comment]
> Have you found out what caused it (to be changed back to `Recommended`?)?

GitLens told me it was last modified by https://github.com/Blitz517.

**Comment by AnonymousWP** [comment]
Fixed with https://github.com/Universal-Debloater-Alliance/universal-android-debloater/pull/59.

Oh by the way, you people use dual-SIM? See description of the package.

**Comment by AnonymousWP** [comment]
> So if it's blitz's fix, maybe there are more mistakes like this one in there? have you checked it?

Perhaps, but it's _a lot_ of work to check all packages for issues, and how would I test all of that? I don't have all phones that exist.

**Comment by AnonymousWP** [comment]
Don't think it's worth it, considering how much time it takes. Blitz is going through a lot of packages already and improves them where possible (see open PRs). Or, if you want of course, feel free to open a PR yourself.

**Comment by fdawans** [comment]
For information, same issue, I couldn't receive SMS messages on Oppo Find X2 Pro after disabling this package (call and sending was OK).
Took me some time to find it!
