### ISSUE TITLE
Android 6.0 Support

### ISSUE THREAD

**Issue by wildheartz** [Universal-Debloater-Alliance/universal-android-debloater#62]
I have tried to debloat an old j2 prime but no app appears in the list, I think there is no support for android 6.0

**Comment by Frigyes06** [comment]
https://github.com/Universal-Debloater-Alliance/universal-android-debloater/wiki/ADB-Reference#pm-disable-user-android-40-sdk-api-18
It should be supported
Can you send logs?

**Comment by Frigyes06** [comment]
Closed due to inactivity.
