### ISSUE TITLE
Removing Samsung contacts app breaks Medical info & Emergency Contacts Section under Safety and Emergency 

### ISSUE THREAD

**Issue by GenTEKS** [Universal-Debloater-Alliance/universal-android-debloater#78]
**Your phone model**:
SM-F936U1

**Packages documentation to update:**

```
com.samsung.android.app.contacts

...
```

## Documentation Change

**List**: `Samsung`|`Misc`|`OEM` 
**Removal**: `Advanced` (this can break important features),
or `Unsafe` (this can bootloop the phone or break extremely important features).

### \<com.samsung.android.app.contacts\>

**List**: \<current list\> :arrow_right: \<proposed list\>
**Removal**: \<current recommendation list\>
:arrow_right: \<proposed recommendation list\>

### Current description

> Current description

### Proposed description

> Add the following:

Removing the contacts app will disable the user from being able to modify the Safety and emergency tab within the Samsung Android native settings app. Specifically the Medical info & Emergency contacts. This information is pulled on the lockscreen by first responders or in emergency sharing mode for emergency contacts.

This feature continues to not work even with a 3rd party app like Google contacts and therefore requires thee proprietary Samsung contacts to be enabled.

**Comment by kyoforkshomebrews** [comment]
### com.samsung.android.app.contacts
**List**: `OEM`
**Removal**: `Advanced`
> Samsung contacts app\nSafe to debloat if you use another contacts app
NOTE : If you do, you will no longer be able to access Contacts from the Samsung dialer app.
>
>Removing the contacts app will disable the user from being able to modify the Safety and emergency tab within the Samsung Android native settings app. Specifically the Medical info & Emergency contacts. This information is pulled on the lockscreen by first responders or in emergency sharing mode for emergency contacts.
