### ISSUE TITLE
Samsung ApexService

### ISSUE THREAD

**Issue by Skizzy24** [Universal-Debloater-Alliance/universal-android-debloater#99]
```
com.sec.android.app.apex
...
```

## Documentation Change

**List**: `Google`|`Misc`|`OEM` (manufacturer)|`AOSP`|`Pending`|`Carrier` (isp).
**Removal**: `Recommended`, `Advanced`, `Expert` (this can break important features),
or `Unsafe` (this can bootloop the phone or break extremely important features).

### \<com.sec.android.app.apex\>

**Removal**: \<Expert\> :arrow_right: \<Recommended\>

### Proposed description

> Without this motion photos will not work see https://www.samsung.com/au/support/mobile-devices/motion-photos

**Comment by AnonymousWP** [comment]
In my opinion this should be Advanced, as it breaks a feature some users may want to use. Changed. Let me know what you think.

**Comment by Skizzy24** [comment]
> In my opinion this should be Advanced, as it breaks a feature some users may want to use. Changed. Let me know what you think.

yeah you are right
